name: Run Unit Tests

on:
  push:
    branches:
      - folder-structure-task
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.1'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        env:
          PIP_EXTRA_INDEX_URL: https://pypi.org/simple

      - name: Run tests
        run: |
          pytest